```tsx
// ...existing code...
export const MeetupProvider = ({ children }: MeetupProviderProps) => {
  // ...existing code...
};
// ...existing code...
export const useMeetups = () => {
  // ...existing code...
};
// ...existing code...
```